### ISSUE TITLE
contact | 上善若水

### ISSUE THREAD

**Issue by xinetzone** [xinetzone/hexo-matery#10]
https://xinetzone.github.io/contact/ 

 contact | 上善若水

**Comment by dongge404** [comment]
请问这个留言板怎么设置？

**Comment by xinetzone** [comment]
> @dongge404
> 请问这个留言板怎么设置？

主要有两种方法：

1. 您需要在 `source/` 目录下面创建 `contact\index.md` 文件，之后写入一些您需要展示的内容即可。
2. 或者直接运行 `hexo new page contact`，然后在 `contact\index.md` 文件中填充内容。

**Comment by dongge404** [comment]
使用这个主题，我的图片怎么弄也显示不了，为什么呀？试了很多方法都不行

**Comment by xinetzone** [comment]
> @dongge404


上传图片使用如下格式：

```markdown
![测试图片](雷姆.png)
```

其中 `雷姆.png` 的位置在您文章同名目录之下

**Comment by Flyiyu** [comment]
大佬你好，配置了很多种评论方式(gitTalk)，都不成功，您是怎样设置的？

**Comment by xinetzone** [comment]
> @dongge404
> 请问这个留言板怎么设置？

参考：https://github.com/gitalk/gitalk/blob/master/readme-cn.md
