### ISSUE TITLE
schedule | 上善若水

### ISSUE THREAD

**Issue by xinetzone** [xinetzone/hexo-matery#18]
https://xinetzone.github.io/schedule/ 

 schedule | 上善若水

**Comment by AllenWrong** [comment]
你好，这个页面是怎么做的

**Comment by xinetzone** [comment]
> @AllenWrong
> 你好，这个页面是怎么做的

直接修改模板中 的 [docs/source/medias/schedule/index.md](https://github.com/xinetzone/xinetzone.github.io/blob/matery/docs/source/medias/schedule/index.md) 即可。

**Comment by AllenWrong** [comment]
> @xinetzone
> > @AllenWrong
> > 你好，这个页面是怎么做的
> 
> 直接修改模板中 的 [docs/source/medias/schedule/index.md](https://github.com/xinetzone/xinetzone.github.io/blob/matery/docs/source/medias/schedule/index.md) 即可。

已收到，感谢
